## Linear Algebra Exercise Pack (Core + Python)


Designed for your Maths–DS–ML Sprint (15 days, 5h/day) David, this pack is meant to be used daily — each block is self‑contained and builds toward DS/ML fluency.


### 📘 Block 7 — Eigenvalues & Eigenvectors





#### Visuals

25. (https://ts3.mm.bing.net/th?id=OIP.3jR4NgWtbnrTv9HPAQ7jnAHaJ2&pid=15.1&o=7&rm=3)
26. (https://ts1.mm.bing.net/th?id=OIP.CIOA6ENQ8kqUHLoUMsgKGQHaEL&pid=15.1&o=7&rm=3)
27. (https://ts4.mm.bing.net/th?id=OIP.lx7bbkyDpc9KGUzyEOgwtQHaGy&pid=15.1&o=7&rm=3)
28. (https://ts3.mm.bing.net/th?id=OIP.NITybem14z3RPKv87FzEPgHaFj&pid=15.1&o=7&rm=3)





#### Definitions


#### Exercises

Compute eigenvalues

Diagonalization test

Geometric interpretation



#### Python tasks

In [11]:
import numpy as np

A1 = np.array([[2,1],[1,2]])
vals1, vecs1 = np.linalg.eig(A)

print("Eigenvalues:", vals1)

print("Eigenvectors:\n", vecs1)
print("*----------")
A2 = np.array([[30,-4,0],[0.8,7,10],[0,3,-10]])

vals2, vecs2 = np.linalg.eig(A2)

print("Eigenvalues:", vals2)

print("Eigenvectors:\n", vecs2)
print("**----------")




Eigenvalues: [0. 7.]
Eigenvectors:
 [[-0.89442719 -0.31622777]
 [ 0.4472136  -0.9486833 ]]
*----------
Eigenvalues: [ 29.85521997   8.75054555 -11.60576552]
Eigenvectors:
 [[ 0.9993419   0.18274596 -0.04532275]
 [ 0.03617119  0.970813   -0.47142194]
 [ 0.00272269  0.15532556  0.88074242]]
**----------
