## Linear Algebra Exercise Pack (Core + Python)


Designed for your Maths–DS–ML Sprint (15 days, 5h/day) David, this pack is meant to be used daily — each block is self‑contained and builds toward DS/ML fluency.


### 📘 Block 1 — Vectors, Operations, and Properties

#### Visuals

1. (https://ts4.mm.bing.net/th?id=OIP.b06OA4v3x3yhQiFNNzbzowHaFj&pid=15.1&o=7)
2. (https://ts4.mm.bing.net/th?id=OIP.88PT0Y30IVK2PQRrmkuI9wHaGu&pid=15.1&o=7)
3. (https://ts1.mm.bing.net/th?id=OIP.oz7DaG7RaHYcqcXIW074GAHaD3&pid=15.1&o=7)
4. (https://ts3.mm.bing.net/th?id=OIP.1UhO6ASi7zDriCtjNOYCYwHaJQ&pid=15.1&o=7)


#### Definitions


#### Exercises

Vector addition — Prove associativity and commutativity using 3D vectors.
Scalar multiplication — Show distributive properties using random vectors.
Zero vector — Demonstrate that 0⋅a=0 and (−1)a=−a.


#### Python tasks

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([-1, 0, 4])
c = np.array([2, 2, 2])

print((a + b) + c, a + (b + c))  # associativity
print(a + b, b + a)              # commutativity
print(0 * a)                     # zero scalar
print(-1 * a)                    # additive inverse


[2 4 9] [2 4 9]
[0 2 7] [0 2 7]
[0 0 0]
[-1 -2 -3]
